"""empty message

Revision ID: 43befc48a8f7
Revises: 860b8efdc477
Create Date: 2024-04-27 17:14:47.572198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43befc48a8f7'
down_revision = '860b8efdc477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'questions', ['question_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
