"""empty message

Revision ID: f02555085811
Revises: 1deacc0ee85d
Create Date: 2024-04-14 14:42:15.154983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f02555085811'
down_revision = '1deacc0ee85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captcha', sa.String(length=100), nullable=False))
        batch_op.drop_column('captchar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('emails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captchar', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('captcha')

    # ### end Alembic commands ###
